meta_title: "Matcher"
meta_description: "Matcher is a matcher to match the matchers"
meta_image: "nyc_try.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@Charlesdp28" # indispensable pour les Twitter Cards
